### ISSUE TITLE
CI lint API is behind authentication

### ISSUE THREAD

**Issue by ccremer** [GabLeRoux/docker-gitlab-ci-lint#15]
Since https://about.gitlab.com/releases/2021/06/01/security-release-gitlab-13-12-2-released/#unauthenticated-ci-lint-api-may-lead-to-information-disclosure-and-ssrf, GitLab CI lint API endpoint requires authentication. Therefore any linting with this docker image has stopped working.

It's not possible to provide the token via `GITLAB_CI_API_URL` like `https://user:sometoken@gitlab.com/api/v4` (I've tried it already).
It needs a `PRIVATE-TOKEN` header as documented in https://docs.gitlab.com/ce/api/lint.html

I'd propose to expose a new environment variable that is added as a header in the curl command in the script.

**Comment by GabLeRoux** [comment]
Thanks for letting me know! I can't fix this today (shouldn't be too long, but lots of meetings today), but I can accept pull requests for this. 

Ideally:

1. The fix in the dockerfile, passing `GITLAB_CI_API_URL` at the right place
2. Updated documentation on how to use and how to setup the token in the CI
3. Updated documentation on how to pass the token when using from command line
4. A proof of this working (screenshot in comment or usage output for confirmation).

That would be lovely :D

**Comment by Obirah** [comment]
Just in case it helps to resolve any pain immediately, this tool already supports authentication: https://gitlab.com/orobardet/gitlab-ci-linter

**Comment by GabLeRoux** [comment]
Nice one, and here's a related issue to expose that tool into a docker image on docker hub:  
https://gitlab.com/orobardet/gitlab-ci-linter/-/issues/22

👍
